export const DEV_GEOMODI_USER = {
  email: "preview@geomodi.local",
  username: "preview",
  role: "admin",
  workspaceName: "GeoModi Lab",
};

export const DEV_GEOMODI_NAV_GROUPS = [
  {
    title: "Operacion",
    items: [
      { id: "dashboard", icon: "📊", label: "Dashboard" },
      { id: "flex", icon: "🚀", label: "Flex" },
      { id: "colecta", icon: "📦", label: "Colecta" },
      { id: "map", icon: "📍", label: "Mapa" },
    ],
  },
  {
    title: "Integraciones",
    items: [
      { id: "tiendanube", icon: "🛒", label: "Tiendanube" },
      { id: "zipnova", icon: "📮", label: "Zipnova" },
    ],
  },
];

export const DEV_GEOMODI_CARRIERS = [
  { name: "flash_caba", display_name: "Flash CABA", color: "#60a5fa" },
  { name: "urbano_norte", display_name: "Urbano Norte", color: "#34d399" },
  { name: "sur_log", display_name: "Sur Log", color: "#f97316" },
  { name: "ramal_oeste", display_name: "Ramal Oeste", color: "#a78bfa" },
];

export const DEV_GEOMODI_SHIPMENTS = [
  {
    id: 6101,
    tracking_number: "GM-0006101",
    product_name: "Teclado mecanico 65%",
    recipient_name: "Lucia Torres",
    address: "Av. Cabildo 2450",
    city: "CABA",
    province: "Buenos Aires",
    partido: "capital_federal",
    zone: "CABA",
    shipping_method: "flex",
    assigned_carrier: "flash_caba",
    status: "despachado",
    units: 1,
    eta: "Hoy 15:30",
    lat: -34.5639,
    lng: -58.4546,
  },
  {
    id: 6102,
    tracking_number: "GM-0006102",
    product_name: "Monitor ultrawide 34\"",
    recipient_name: "Martin Acosta",
    address: "Belgrano 881",
    city: "San Isidro",
    province: "Buenos Aires",
    partido: "san_isidro",
    zone: "GBA 1",
    shipping_method: "flex",
    assigned_carrier: "urbano_norte",
    status: "en ruta",
    units: 1,
    eta: "Hoy 16:10",
    lat: -34.4721,
    lng: -58.5164,
  },
  {
    id: 6103,
    tracking_number: "GM-0006103",
    product_name: "Silla gamer ergonica",
    recipient_name: "Carla Medina",
    address: "Av. Hipolito Yrigoyen 4321",
    city: "Lanus",
    province: "Buenos Aires",
    partido: "lanus",
    zone: "GBA 1",
    shipping_method: "flex",
    assigned_carrier: "sur_log",
    status: "despachado",
    units: 2,
    eta: "Hoy 17:00",
    lat: -34.7044,
    lng: -58.3938,
  },
  {
    id: 6104,
    tracking_number: "GM-0006104",
    product_name: "Impresora termica Zebra",
    recipient_name: "Nicolas Ruiz",
    address: "Ruta 3 km 23",
    city: "La Matanza",
    province: "Buenos Aires",
    partido: "la_matanza",
    zone: "GBA 2",
    shipping_method: "flex",
    assigned_carrier: "",
    status: "pendiente",
    units: 1,
    eta: "Esperando asignacion",
    lat: -34.6708,
    lng: -58.6264,
  },
  {
    id: 6105,
    tracking_number: "GM-0006105",
    product_name: "Router WiFi 6 mesh",
    recipient_name: "Julian Pereyra",
    address: "Calchaqui 1920",
    city: "Quilmes",
    province: "Buenos Aires",
    partido: "quilmes",
    zone: "GBA 2",
    shipping_method: "flex",
    assigned_carrier: "sur_log",
    status: "despachado",
    units: 3,
    eta: "Hoy 18:20",
    lat: -34.7242,
    lng: -58.2527,
  },
  {
    id: 6106,
    tracking_number: "GM-0006106",
    product_name: "Parlante bluetooth IPX7",
    recipient_name: "Paula Varela",
    address: "Caamano 1100",
    city: "Pilar",
    province: "Buenos Aires",
    partido: "pilar",
    zone: "GBA 3",
    shipping_method: "flex",
    assigned_carrier: "ramal_oeste",
    status: "entregado",
    units: 1,
    eta: "Entregado 12:45",
    lat: -34.4579,
    lng: -58.9131,
  },
  {
    id: 6201,
    tracking_number: "GM-0006201",
    product_name: "Caja de accesorios smart home",
    recipient_name: "Ana Rios",
    address: "San Martin 1560",
    city: "Rosario",
    province: "Santa Fe",
    partido: "rosario",
    zone: "Interior",
    shipping_method: "colecta",
    assigned_carrier: "",
    status: "clasificando",
    units: 4,
    eta: "Manana",
    lat: -32.9442,
    lng: -60.6505,
  },
  {
    id: 6202,
    tracking_number: "GM-0006202",
    product_name: "Tablet 10 pulgadas",
    recipient_name: "Rocio Sosa",
    address: "Colon 345",
    city: "Cordoba",
    province: "Cordoba",
    partido: "cordoba",
    zone: "Interior",
    shipping_method: "colecta",
    assigned_carrier: "",
    status: "en hub",
    units: 2,
    eta: "Manana 09:00",
    lat: -31.4201,
    lng: -64.1888,
  },
  {
    id: 6203,
    tracking_number: "GM-0006203",
    product_name: "Aspiradora inalambrica",
    recipient_name: "Federico Moya",
    address: "Godoy Cruz 210",
    city: "Mendoza",
    province: "Mendoza",
    partido: "mendoza",
    zone: "Interior",
    shipping_method: "colecta",
    assigned_carrier: "",
    status: "despachado",
    units: 1,
    eta: "Manana 13:30",
    lat: -32.8895,
    lng: -68.8458,
  },
  {
    id: 6204,
    tracking_number: "GM-0006204",
    product_name: "Cafetera programable",
    recipient_name: "Micaela Mendez",
    address: "Luro 5021",
    city: "Mar del Plata",
    province: "Buenos Aires",
    partido: "general_pueyrredon",
    zone: "Costa",
    shipping_method: "colecta",
    assigned_carrier: "",
    status: "pendiente",
    units: 1,
    eta: "Pendiente de salida",
    lat: -38.0055,
    lng: -57.5426,
  },
  {
    id: 6205,
    tracking_number: "GM-0006205",
    product_name: "Control de acceso RFID",
    recipient_name: "Leandro Diaz",
    address: "Av. Argentina 720",
    city: "Neuquen",
    province: "Neuquen",
    partido: "neuquen",
    zone: "Patagonia",
    shipping_method: "colecta",
    assigned_carrier: "",
    status: "en ruta",
    units: 2,
    eta: "Viernes",
    lat: -38.9516,
    lng: -68.0591,
  },
  {
    id: 6107,
    tracking_number: "GM-0006107",
    product_name: "Kit PoE camaras x4",
    recipient_name: "Sergio Vega",
    address: "Av. Rivadavia 9210",
    city: "CABA",
    province: "Buenos Aires",
    partido: "capital_federal",
    zone: "CABA",
    shipping_method: "flex",
    assigned_carrier: "flash_caba",
    status: "entregado",
    units: 1,
    eta: "Entregado 11:20",
    lat: -34.6263,
    lng: -58.4926,
  },
];

export const DEV_GEOMODI_TIENDANUBE_META = {
  connectedAt: "2026-04-23T08:12:00-03:00",
  lastSyncedAt: "2026-04-23T14:18:00-03:00",
};

export const DEV_GEOMODI_TIENDANUBE_ORDERS = [
  {
    id: 91001,
    number: 1051,
    total: 48999,
    currency: "ARS",
    createdAt: "2026-04-23T09:10:00-03:00",
    contactName: "Lucia Torres",
    contactEmail: "lucia.torres@mockmail.com",
    shippingCarrier: "GeoModi Flex",
    shippingMethod: "Same Day",
    shippingStatus: "ready_to_ship",
    dispatchStatus: "to_send",
    dispatchMarkedAt: "",
    dispatchMarkedBy: "",
    products: [
      { name: "Auriculares Studio Pro", quantity: 1 },
      { name: "Cable balanceado 2 m", quantity: 1 },
    ],
    shippingAddress: {
      address: "Av. Cabildo",
      number: "2450",
      city: "CABA",
      province: "Buenos Aires",
      zipcode: "1428",
    },
  },
  {
    id: 91002,
    number: 1052,
    total: 129500,
    currency: "ARS",
    createdAt: "2026-04-23T09:42:00-03:00",
    contactName: "Martin Acosta",
    contactEmail: "martin.acosta@mockmail.com",
    shippingCarrier: "GeoModi Flex",
    shippingMethod: "AMBA PM",
    shippingStatus: "packed",
    dispatchStatus: "to_send",
    dispatchMarkedAt: "",
    dispatchMarkedBy: "",
    products: [
      { name: "Monitor ultrawide 34\"", quantity: 1 },
    ],
    shippingAddress: {
      address: "Belgrano",
      number: "881",
      city: "San Isidro",
      province: "Buenos Aires",
      zipcode: "1642",
    },
  },
  {
    id: 91003,
    number: 1053,
    total: 35990,
    currency: "ARS",
    createdAt: "2026-04-23T10:05:00-03:00",
    contactName: "Carla Medina",
    contactEmail: "carla.medina@mockmail.com",
    shippingCarrier: "Andreani",
    shippingMethod: "Domicilio",
    shippingStatus: "shipped",
    dispatchStatus: "dispatched",
    dispatchMarkedAt: "2026-04-23T12:22:00-03:00",
    dispatchMarkedBy: "preview@geomodi.local",
    products: [
      { name: "Router WiFi 6 Mesh", quantity: 1 },
      { name: "Nodo satelite AX", quantity: 2 },
    ],
    shippingAddress: {
      address: "Calchaqui",
      number: "1920",
      city: "Quilmes",
      province: "Buenos Aires",
      zipcode: "1878",
    },
  },
  {
    id: 91004,
    number: 1054,
    total: 79990,
    currency: "ARS",
    createdAt: "2026-04-23T10:36:00-03:00",
    contactName: "Julian Pereyra",
    contactEmail: "julian.pereyra@mockmail.com",
    shippingCarrier: "GeoModi Flex",
    shippingMethod: "Express Oeste",
    shippingStatus: "unshipped",
    dispatchStatus: "to_send",
    dispatchMarkedAt: "",
    dispatchMarkedBy: "",
    products: [
      { name: "Impresora termica Zebra", quantity: 1 },
      { name: "Rollo 100x150", quantity: 3 },
      { name: "Kit limpieza cabezal", quantity: 1 },
    ],
    shippingAddress: {
      address: "Ruta 3 km 23",
      number: "",
      city: "La Matanza",
      province: "Buenos Aires",
      zipcode: "1754",
    },
  },
  {
    id: 91005,
    number: 1055,
    total: 22890,
    currency: "ARS",
    createdAt: "2026-04-23T11:12:00-03:00",
    contactName: "Paula Varela",
    contactEmail: "paula.varela@mockmail.com",
    shippingCarrier: "Correo Argentino",
    shippingMethod: "Clasico",
    shippingStatus: "delivered",
    dispatchStatus: "dispatched",
    dispatchMarkedAt: "2026-04-23T13:40:00-03:00",
    dispatchMarkedBy: "preview@geomodi.local",
    products: [
      { name: "Parlante bluetooth IPX7", quantity: 2 },
    ],
    shippingAddress: {
      address: "Caamano",
      number: "1100",
      city: "Pilar",
      province: "Buenos Aires",
      zipcode: "1629",
    },
  },
  {
    id: 91006,
    number: 1056,
    total: 94500,
    currency: "ARS",
    createdAt: "2026-04-23T11:48:00-03:00",
    contactName: "Rocio Sosa",
    contactEmail: "rocio.sosa@mockmail.com",
    shippingCarrier: "GeoModi Flex",
    shippingMethod: "Same Day",
    shippingStatus: "ready_to_ship",
    dispatchStatus: "to_send",
    dispatchMarkedAt: "",
    dispatchMarkedBy: "",
    products: [
      { name: "Tablet 10 pulgadas", quantity: 1 },
      { name: "Funda magnetica", quantity: 1 },
    ],
    shippingAddress: {
      address: "Av. Rivadavia",
      number: "9210",
      city: "CABA",
      province: "Buenos Aires",
      zipcode: "1407",
    },
  },
];

export const DEV_GEOMODI_ZIPNOVA_META = {
  connectedAt: "2026-04-23T08:04:00-03:00",
  lastSyncedAt: "2026-04-23T14:05:00-03:00",
};

export const DEV_GEOMODI_ZIPNOVA_SHIPMENTS = [
  {
    id: 73001,
    external_id: "ZN-240423-001",
    status: "processing",
    status_name: "Procesando",
    total_packages: 2,
    products: [
      { sku: "HUB-USB-C", name: "Hub USB-C 8 puertos" },
      { sku: "HUB-USB-C", name: "Hub USB-C 8 puertos" },
    ],
    downloaded_at: "",
    downloaded_by: "",
  },
  {
    id: 73002,
    external_id: "ZN-240423-002",
    status: "awaiting_documentation",
    status_name: "Esperando documentacion",
    total_packages: 1,
    products: [
      { sku: "CAM-POE-4", name: "Kit camaras PoE x4" },
    ],
    downloaded_at: "",
    downloaded_by: "",
  },
  {
    id: 73003,
    external_id: "ZN-240423-003",
    status: "documentation_ready",
    status_name: "Documentacion lista",
    total_packages: 3,
    products: [
      { sku: "ZEBRA-ZD421", name: "Impresora Zebra ZD421" },
      { sku: "ROLLO-100X150", name: "Rollo 100x150" },
    ],
    downloaded_at: "",
    downloaded_by: "",
  },
  {
    id: 73004,
    external_id: "ZN-240423-004",
    status: "ready_to_ship",
    status_name: "Listo para despacho",
    total_packages: 2,
    products: [
      { sku: "TABLET-10", name: "Tablet 10 pulgadas" },
    ],
    downloaded_at: "2026-04-23T13:12:00-03:00",
    downloaded_by: "preview@geomodi.local",
  },
  {
    id: 73005,
    external_id: "ZN-240423-005",
    status: "processing",
    status_name: "En armado",
    total_packages: 4,
    products: [
      { sku: "SILLA-GMR", name: "Silla gamer ergonomica" },
      { sku: "SILLA-GMR", name: "Silla gamer ergonomica" },
    ],
    downloaded_at: "",
    downloaded_by: "",
  },
  {
    id: 73006,
    external_id: "ZN-240423-006",
    status: "ready_to_ship",
    status_name: "Listo para retiro",
    total_packages: 1,
    products: [
      { sku: "RFID-CTRL", name: "Control de acceso RFID" },
    ],
    downloaded_at: "",
    downloaded_by: "",
  },
];
