"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, toast } from "@/lib/api";
import { useBatch } from "./BatchContext";
const zoneOf = (s) => s.partido || s.city || "Sin zona";
function argentinaDate(offset = 0) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const value = Object.fromEntries(parts.map(({ type, value }) => [type, value])); const date = new Date(`${value.year}-${value.month}-${value.day}T12:00:00Z`); date.setUTCDate(date.getUTCDate() - offset); return date.toISOString().slice(0, 10); }

export default function FlexSection() {
  const { getTodayQueryString } = useBatch();
  const [shipments, setShipments] = useState([]), [carriers, setCarriers] = useState([]), [portals, setPortals] = useState([]), [settings, setSettings] = useState(null), [loading, setLoading] = useState(true), [moving, setMoving] = useState(new Set()), [selected, setSelected] = useState(new Set()), [target, setTarget] = useState(""), [query, setQuery] = useState(""), [dragged, setDragged] = useState(null), [showControls, setShowControls] = useState(false), [dateOffset, setDateOffset] = useState(0);
  const load = useCallback(async ({ silent = false } = {}) => { if (!silent) setLoading(true); try { const period = dateOffset ? `period=date&date=${argentinaDate(dateOffset)}` : getTodayQueryString(); const [items, cs, ps, ss] = await Promise.all([api(`/shipments?${period}&shipping_method=flex`), api("/carriers"), api("/carrier-portals"), api("/flex-portal-settings")]); setShipments(Array.isArray(items) ? items : []); setCarriers(cs || []); setPortals(ps || []); setSettings(ss || null); } catch (e) { toast(e.message || "No se pudo cargar Flex", "error"); } finally { if (!silent) setLoading(false); } }, [dateOffset, getTodayQueryString]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const sync = () => document.visibilityState === "visible" && load({ silent: true }); const timer = setInterval(sync, 10000); addEventListener("focus", sync); return () => { clearInterval(timer); removeEventListener("focus", sync); }; }, [load]);
  const filtered = useMemo(() => shipments.filter((s) => !query.trim() || [s.product_name, s.sku, s.partido, s.assigned_carrier].join(" ").toLowerCase().includes(query.trim().toLowerCase())), [shipments, query]);
  const unassigned = filtered.filter((s) => !s.assigned_carrier); const byCarrier = useMemo(() => Object.fromEntries(carriers.map((c) => [c.name, filtered.filter((s) => s.assigned_carrier === c.name)])), [carriers, filtered]);
  const move = async (ids, carrierName) => { const valid = [...new Set(ids)].filter((id) => !moving.has(id)); if (!valid.length || !carrierName) return; const old = shipments; setMoving((x) => new Set([...x, ...valid])); setShipments((x) => x.map((s) => valid.includes(s.id) ? { ...s, assigned_carrier: carrierName } : s)); try { const r = await api("/shipments/flex-assignments", { method: "PATCH", body: JSON.stringify({ ids: valid, carrierName }) }); setSelected((x) => new Set([...x].filter((id) => !valid.includes(id)))); toast(`${valid.length} ${valid.length === 1 ? "paquete movido" : "paquetes movidos"} a ${r.carrierDisplayName}`, "success"); } catch (e) { setShipments(old); toast(e.message || "No se pudo mover. Intentá de nuevo.", "error"); } finally { setMoving((x) => new Set([...x].filter((id) => !valid.includes(id)))); } };
  const toggle = (id) => setSelected((x) => { const n = new Set(x); n.has(id) ? n.delete(id) : n.add(id); return n; });
  const saveCutoff = async (cutoffTime) => { try { const s = await api("/flex-portal-settings", { method: "PATCH", body: JSON.stringify({ cutoffTime: cutoffTime || null }) }); setSettings(s); toast("Horario guardado", "success"); } catch (e) { toast(e.message || "No se pudo guardar", "error"); } };
  const publish = async () => { try { const s = await api("/flex-portal-settings", { method: "POST" }); setSettings(s); toast("Operación publicada para hoy", "success"); } catch (e) { toast(e.message || "No se pudo publicar", "error"); } };
  const copy = async (carrier) => { const url = portals.find((p) => p.carrier_id === carrier.id)?.portal?.url; if (!url) return toast("Link no disponible", "error"); try { await navigator.clipboard.writeText(url); toast("Link copiado", "success"); } catch { toast("No se pudo copiar el link", "error"); } };
  const createOrCopyLink = async (carrier) => { const current = portals.find((p) => p.carrier_id === carrier.id)?.portal; if (current?.url) return copy(carrier); try { const response = await api("/carrier-portals", { method: "POST", body: JSON.stringify({ carrierId: carrier.id }) }); setPortals((items) => { const rest = items.filter((item) => item.carrier_id !== carrier.id); return [...rest, { carrier_id: carrier.id, portal: response.portal }]; }); await navigator.clipboard.writeText(response.portal.url); toast(`Link de ${carrier.display_name || carrier.name} creado y copiado`, "success"); } catch (error) { toast(error.message || "No se pudo crear el link", "error"); } };
  const Card = ({ shipment }) => { const busy = moving.has(shipment.id), c = carriers.find((x) => x.name === shipment.assigned_carrier); return <article className={`flex-board-card ${busy ? "is-saving" : ""}`} draggable={!busy} onDragStart={() => setDragged(shipment.id)} onDragEnd={() => setDragged(null)}><label className="flex-card-check"><input type="checkbox" checked={selected.has(shipment.id)} onChange={() => toggle(shipment.id)} aria-label={`Seleccionar ${shipment.product_name}`} /></label><div className="flex-card-main"><strong title={shipment.product_name}>{shipment.product_name || "Producto sin nombre"}</strong><span>{shipment.sku ? `SKU ${shipment.sku}` : "Sin SKU"} · {zoneOf(shipment)}</span></div><select value={shipment.assigned_carrier || ""} onChange={(e) => move([shipment.id], e.target.value)} disabled={busy} aria-label={`Transportista de ${shipment.product_name}`} style={c?.color ? { borderColor: c.color } : undefined}><option value="">Sin asignar</option>{carriers.map((x) => <option value={x.name} key={x.id}>{x.display_name || x.name}</option>)}</select>{busy && <span className="flex-saving" role="status">Guardando</span>}</article>; };
  const Lane = ({ carrier, items }) => { const hasLink = Boolean(portals.find((p) => p.carrier_id === carrier.id)?.portal?.url); return <section className="flex-lane" onDragOver={(e) => e.preventDefault()} onDrop={() => { if (dragged) move(selected.has(dragged) ? [...selected] : [dragged], carrier.name); setDragged(null); }}><header style={{ "--lane": carrier.color || "var(--accent)" }}><span className="flex-lane-dot" /><div><strong>{carrier.display_name || carrier.name}</strong><small>{items.length} paquetes</small></div><button type="button" onClick={() => createOrCopyLink(carrier)}>{hasLink ? "Copiar link" : "Crear link"}</button></header><div className="flex-lane-list">{items.map((s) => <Card shipment={s} key={s.id} />)}{!items.length && <p className="flex-lane-empty">Arrastrá paquetes acá</p>}</div></section>; };
  if (loading) return <section className="section active"><div className="spinner" /></section>;
  const scheduleEnabled = Boolean(settings?.cutoffTime);
  return <section className="section active flex-board"><header className="flex-board-head"><div><p className="flex-eyebrow">OPERACIÓN · FLEX</p><h1>Distribución</h1><span>{shipments.length} paquetes · {carriers.length} transportistas</span></div><div className="flex-board-actions"><button className={`btn btn-sm ${dateOffset === 0 ? "btn-primary" : ""}`} type="button" onClick={() => setDateOffset(0)}>Hoy</button><button className={`btn btn-sm ${dateOffset === 1 ? "btn-primary" : ""}`} type="button" onClick={() => setDateOffset(1)}>Ayer</button><span className={`flex-live ${settings?.state === "scheduled" ? "scheduled" : ""}`}>{dateOffset ? `Operación ${argentinaDate(1)}` : settings?.state === "scheduled" ? `Disponible ${settings.cutoffTime}` : "En vivo"}</span><button className="btn btn-sm" type="button" onClick={() => setShowControls((x) => !x)}>Configuración de horario</button></div></header>{showControls && <aside className="flex-publication-panel"><div className="flex-schedule-copy"><strong>¿Cuándo ven los paquetes?</strong><p>Al activarlo, los links de los transportistas ocultan los paquetes de hoy hasta la hora elegida. Con el horario desactivado, cada paquete aparece apenas ingresa.</p></div><label className="flex-schedule-toggle"><input type="checkbox" checked={scheduleEnabled} onChange={(e) => saveCutoff(e.target.checked ? (settings?.cutoffTime || "09:00") : null)} /><span>Activar horario de publicación</span></label>{scheduleEnabled && <label>Hora Argentina<input type="time" value={settings.cutoffTime} onChange={(e) => saveCutoff(e.target.value)} /></label>}<button type="button" className="btn btn-primary btn-sm" onClick={publish} disabled={!scheduleEnabled || settings?.state === "live"}>Enviar paquetes ahora</button></aside>}<div className="flex-board-toolbar"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar producto, SKU o zona" aria-label="Buscar paquetes Flex" /><span>{selected.size ? `${selected.size} seleccionados` : "Arrastrá o seleccioná paquetes"}</span><select value={target} onChange={(e) => setTarget(e.target.value)} aria-label="Destino de la selección"><option value="">Mover selección a…</option>{carriers.map((c) => <option key={c.id} value={c.name}>{c.display_name || c.name}</option>)}</select><button type="button" className="btn btn-primary btn-sm" disabled={!selected.size || !target} onClick={() => move([...selected], target)}>Mover</button></div>{unassigned.length > 0 && <section className="flex-unassigned"><strong>Sin asignar · {unassigned.length}</strong><div>{unassigned.map((s) => <Card shipment={s} key={s.id} />)}</div></section>}<main className="flex-lanes" aria-label="Tablero de transportistas">{carriers.map((c) => <Lane key={c.id} carrier={c} items={byCarrier[c.name] || []} />)}</main></section>;
}
